"""Add LLM failure log table

Revision ID: 8fbbecdb02c8
Revises: a97640b4fa62
Create Date: 2026-07-17 13:47:27.626595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbbecdb02c8'
down_revision: Union[str, Sequence[str], None] = 'a97640b4fa62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_failure_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('selection_id', sa.Uuid(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_failure_logs')
    # ### end Alembic commands ###
